// Code generated by tablesgen; DO NOT EDIT.
// Regenerate with `WAXFLOW_FFMPEG_SRC=... go generate ./codec/wma`.
//
// Black-box parameter artifact (ADR-0001): data only, no decoder logic. WMA
// has no published bitstream spec, so these are extracted from FFmpeg's data
// files, pinned by SHA-256 in tablesgen_test.go, rather than restated from a
// normative document. See THIRD-PARTY-NOTICES.md and docs/notes/wma-bitstream.md.

package wma

// VLC-coded exponents (flags2 bit 0 set) are DPCM-coded with the AAC
// scalefactor book biased by -60: the same 121-entry book
// codec/aac/tables_hcb.go carries, duplicated here only because neither
// package imports the other.

var expScaleCodes = [121]uint32{
	0x3ffe8, 0x3ffe6, 0x3ffe7, 0x3ffe5, 0x7fff5, 0x7fff1, 0x7ffed, 0x7fff6,
	0x7ffee, 0x7ffef, 0x7fff0, 0x7fffc, 0x7fffd, 0x7ffff, 0x7fffe, 0x7fff7,
	0x7fff8, 0x7fffb, 0x7fff9, 0x3ffe4, 0x7fffa, 0x3ffe3, 0x1ffef, 0x1fff0,
	0xfff5, 0x1ffee, 0xfff2, 0xfff3, 0xfff4, 0xfff1, 0x7ff6, 0x7ff7,
	0x3ff9, 0x3ff5, 0x3ff7, 0x3ff3, 0x3ff6, 0x3ff2, 0x1ff7, 0x1ff5,
	0xff9, 0xff7, 0xff6, 0x7f9, 0xff4, 0x7f8, 0x3f9, 0x3f7,
	0x3f5, 0x1f8, 0x1f7, 0xfa, 0xf8, 0xf6, 0x79, 0x3a,
	0x38, 0x1a, 0xb, 0x4, 0x0, 0xa, 0xc, 0x1b,
	0x39, 0x3b, 0x78, 0x7a, 0xf7, 0xf9, 0x1f6, 0x1f9,
	0x3f4, 0x3f6, 0x3f8, 0x7f5, 0x7f4, 0x7f6, 0x7f7, 0xff5,
	0xff8, 0x1ff4, 0x1ff6, 0x1ff8, 0x3ff8, 0x3ff4, 0xfff0, 0x7ff4,
	0xfff6, 0x7ff5, 0x3ffe2, 0x7ffd9, 0x7ffda, 0x7ffdb, 0x7ffdc, 0x7ffdd,
	0x7ffde, 0x7ffd8, 0x7ffd2, 0x7ffd3, 0x7ffd4, 0x7ffd5, 0x7ffd6, 0x7fff2,
	0x7ffdf, 0x7ffe7, 0x7ffe8, 0x7ffe9, 0x7ffea, 0x7ffeb, 0x7ffe6, 0x7ffe0,
	0x7ffe1, 0x7ffe2, 0x7ffe3, 0x7ffe4, 0x7ffe5, 0x7ffd7, 0x7ffec, 0x7fff4,
	0x7fff3,
}

var expScaleBits = [121]uint8{
	18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 18,
	19, 18, 17, 17, 16, 17, 16, 16, 16, 16, 15, 15, 14, 14, 14, 14, 14, 14, 13, 13,
	12, 12, 12, 11, 12, 11, 10, 10, 10, 9, 9, 8, 8, 8, 7, 6, 6, 5, 4, 3,
	1, 4, 4, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 10, 11, 11, 11, 11, 12,
	12, 13, 13, 13, 14, 14, 16, 15, 16, 15, 18, 19, 19, 19, 19, 19, 19, 19, 19, 19,
	19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19,
	19,
}

// hgainHuff is the noise-gain book as {symbol, length} pairs in canonical code
// order. The symbol is biased: the gain delta it stands for is symbol-18.

var hgainHuff = [37][2]uint8{
	{25, 10},
	{2, 10},
	{27, 10},
	{0, 10},
	{31, 9},
	{30, 9},
	{23, 8},
	{7, 8},
	{29, 8},
	{26, 8},
	{24, 7},
	{10, 5},
	{12, 4},
	{20, 5},
	{22, 6},
	{8, 7},
	{33, 10},
	{32, 13},
	{5, 13},
	{34, 13},
	{35, 13},
	{36, 13},
	{3, 13},
	{1, 12},
	{4, 9},
	{6, 9},
	{28, 9},
	{18, 4},
	{16, 4},
	{21, 5},
	{9, 5},
	{11, 4},
	{19, 4},
	{14, 3},
	{15, 3},
	{13, 3},
	{17, 3},
}

// lspCodebook holds the ten LSP coefficient rows read when exponents are LSP
// coded (flags2 bit 0 clear). Rows 0 and 8..9 are read with 3 bits and so use
// their first eight entries; the rest are read with 4 bits and use all
// sixteen. Row 5 entry 10 breaks that row's monotone descent and is
// reproduced as upstream has it, since matching deployed decoders is the
// whole point of the table (docs/notes/wma-bitstream.md, "The one entry that
// looks wrong").

var lspCodebook = [nbLSPCoefs][16]float32{
	{
		1.98732877, 1.97944528, 1.97179088, 1.96260549,
		1.95038374, 1.93336114, 1.90719232, 1.86191415,
	},
	{
		1.97260000, 1.96083160, 1.94982586, 1.93806164,
		1.92516608, 1.91010199, 1.89232331, 1.87149812,
		1.84564818, 1.81358067, 1.77620070, 1.73265264,
		1.67907855, 1.60959081, 1.50829650, 1.33120330,
	},
	{
		1.90109110, 1.86482426, 1.83419671, 1.80168452,
		1.76650116, 1.72816320, 1.68502700, 1.63738256,
		1.58501580, 1.51795181, 1.43679906, 1.33950585,
		1.24176208, 1.12260729, 0.96749668, 0.74048265,
	},
	{
		1.76943864, 1.67822463, 1.59946365, 1.53560582,
		1.47470796, 1.41210167, 1.34509536, 1.27339507,
		1.19303814, 1.09765169, 0.98818722, 0.87239446,
		0.74369172, 0.59768184, 0.43168630, 0.17977021,
	},
	{
		1.43428349, 1.32038354, 1.21074086, 1.10577988,
		1.00561746, 0.90335924, 0.80437489, 0.70709671,
		0.60427395, 0.49814048, 0.38509539, 0.27106800,
		0.14407416, 0.00219910, -0.16725141, -0.36936085,
	},
	{
		0.99895687, 0.84188166, 0.70753739, 0.57906595,
		0.47055563, 0.36966965, 0.26826648, 0.17163380,
		0.07208392, -0.03062936, -1.40037388, -0.25128968,
		-0.37213937, -0.51075646, -0.64887512, -0.80308031,
	},
	{
		0.26515280, 0.06313551, -0.08872080, -0.21103548,
		-0.31069678, -0.39680323, -0.47223474, -0.54167135,
		-0.61444740, -0.68943343, -0.76580211, -0.85170082,
		-0.95289061, -1.06514703, -1.20510707, -1.37617746,
	},
	{
		-0.53940301, -0.73770929, -0.88424876, -1.01117930,
		-1.13389091, -1.26830073, -1.42041987, -1.62033919,
		-1.10158808, -1.16512566, -1.23337128, -1.30414401,
		-1.37663312, -1.46853845, -1.57625798, -1.66893638,
	},
	{
		-0.38601997, -0.56009350, -0.66978483, -0.76028471,
		-0.83846064, -0.90868087, -0.97408881, -1.03694962,
	},
	{
		-1.56144989, -1.65944032, -1.72689685, -1.77857740,
		-1.82203011, -1.86220079, -1.90283983, -1.94820479,
	},
}
