//go:build wmatablesgen

package wma

// Offline extraction of the WMA parameter tables (ADR-0001). Run with:
//
//	WAXFLOW_FFMPEG_SRC=/path/to/ffmpeg/libavcodec go generate ./codec/wma
//
// which is wired to `go test -tags wmatablesgen -run ^TestGenerateTables$`.
//
// WMA is the one codec here with no published bitstream spec, so its tables
// cannot be restated from a normative document the way the AAC and SBR tables
// are. They are extracted instead, mechanically and under a SHA-256 pin, from
// FFmpeg's data files, in the analysis pass ADR-0001 separates from
// implementation. Mechanically matters: four thousand numbers cannot be
// transcribed by hand and then be trusted, and a reviewer can re-run this
// against the pinned upstream and diff the result.
//
// The pinned files are data, not logic. wmadata.h holds the coefficient
// books, the noise-gain book, the LSP codebook and the tabulated v2 exponent
// bands; wma_freqs.c holds the critical-band edges; aactab.c holds the
// scalefactor book WMA reuses for VLC-coded exponents.

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

// Pinned upstream: FFmpeg n9.0, commit d32b387f2b0a484599d4587d651891f0c63c4238.
// A changed digest fails loudly rather than silently regenerating different
// tables, the discipline internal/testutil.Vectors uses for fetched vectors.
var pinned = map[string]string{
	"wmadata.h":   "e5b8583007d92d5309078c97a319bac42d2fe33617814bfe8bb88ae9724d6bbf",
	"wma_freqs.c": "c8992e806736dd708015c2121bf1773e4c4bbf3201840cbdf7f6c5f3754ee46c",
	"aactab.c":    "dc26f9316026cd807617db09c72424ae2b19b07a1d9c19a45cc05ab9617a32ce",
}

func TestGenerateTables(t *testing.T) {
	dir := os.Getenv("WAXFLOW_FFMPEG_SRC")
	if dir == "" {
		t.Fatal("set WAXFLOW_FFMPEG_SRC to a checked-out ffmpeg libavcodec/ directory")
	}
	src := map[string]string{}
	for name, want := range pinned {
		b, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			t.Fatalf("read %s: %v", name, err)
		}
		b = bytes.ReplaceAll(b, []byte("\r\n"), []byte("\n"))
		// An empty pin prints the digest it would need, which is how a new
		// upstream file gets pinned in the first place.
		if got := hex.EncodeToString(sha256Sum(b)); got != want {
			t.Fatalf("%s: digest %s, pinned %q", name, got, want)
		}
		src[name] = string(b)
	}

	writeFile(t, "tables_coef.go", emitCoef(t, src["wmadata.h"]))
	writeFile(t, "tables_exp.go", emitExp(t, src["wmadata.h"], src["aactab.c"]))
	writeFile(t, "tables_bands.go", emitBands(t, src["wmadata.h"], src["wma_freqs.c"]))
}

func sha256Sum(b []byte) []byte { s := sha256.Sum256(b); return s[:] }

const genHeader = "// Code generated by tablesgen; DO NOT EDIT.\n" +
	"// Regenerate with `WAXFLOW_FFMPEG_SRC=... go generate ./codec/wma`.\n" +
	"//\n" +
	"// Black-box parameter artifact (ADR-0001): data only, no decoder logic. WMA\n" +
	"// has no published bitstream spec, so these are extracted from FFmpeg's data\n" +
	"// files, pinned by SHA-256 in tablesgen_test.go, rather than restated from a\n" +
	"// normative document. See THIRD-PARTY-NOTICES.md and docs/notes/wma-bitstream.md.\n" +
	"\n" +
	"package wma\n"

func writeFile(t *testing.T, name, body string) {
	t.Helper()
	out, err := format.Source([]byte(genHeader + body))
	if err != nil {
		t.Fatalf("%s: gofmt: %v", name, err)
	}
	if err := os.WriteFile(name, out, 0o644); err != nil {
		t.Fatal(err)
	}
	t.Logf("wrote %s (%d bytes)", name, len(out))
}

// --- C initializer parsing -------------------------------------------------

// node is one parsed C initializer: a scalar when kids is nil, otherwise a
// brace group. The tables here nest at most two deep.
type node struct {
	val  string
	kids []node
}

func (n node) flat() []string {
	if n.kids == nil {
		return []string{n.val}
	}
	var out []string
	for _, k := range n.kids {
		out = append(out, k.flat()...)
	}
	return out
}

// initializer returns the brace group of the named C array. Comments come off
// before the search, so a name mentioned in prose ahead of its declaration
// cannot capture it, and the match needs a non-identifier character to its
// left, so `levels0` does not latch onto a longer name ending in it. Both
// would otherwise parse the wrong array and still compile.
func initializer(t *testing.T, src, name string) node {
	t.Helper()
	src = stripComments(src)
	at := -1
	for i := 0; ; {
		j := strings.Index(src[i:], name+"[")
		if j < 0 {
			break
		}
		j += i
		if j == 0 || !isIdentByte(src[j-1]) {
			at = j
			break
		}
		i = j + 1
	}
	if at < 0 {
		t.Fatalf("%s: no declaration found", name)
	}
	j := strings.IndexByte(src[at:], '{')
	if j < 0 {
		t.Fatalf("%s: no initializer", name)
	}
	body, _ := parseGroup(t, src[at+j:], 0)
	return body
}

func isIdentByte(c byte) bool {
	return c == '_' || c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9'
}

func stripComments(s string) string {
	var b strings.Builder
	for i := 0; i < len(s); {
		switch {
		case strings.HasPrefix(s[i:], "/*"):
			e := strings.Index(s[i+2:], "*/")
			if e < 0 {
				return b.String()
			}
			i += 2 + e + 2
		case strings.HasPrefix(s[i:], "//"):
			e := strings.IndexByte(s[i:], '\n')
			if e < 0 {
				return b.String()
			}
			i += e
		default:
			b.WriteByte(s[i])
			i++
		}
	}
	return b.String()
}

// parseGroup consumes the brace group starting at s[at] and returns it plus
// the index just past its closing brace.
func parseGroup(t *testing.T, s string, at int) (node, int) {
	t.Helper()
	if s[at] != '{' {
		t.Fatalf("expected a brace group at %d", at)
	}
	out := node{kids: []node{}}
	var tok strings.Builder
	flush := func() {
		v := strings.TrimSpace(tok.String())
		tok.Reset()
		if v != "" {
			out.kids = append(out.kids, node{val: v})
		}
	}
	for i := at + 1; i < len(s); {
		switch c := s[i]; c {
		case '{':
			// Flush first: a scalar sitting before a nested group belongs
			// ahead of it, and appending the group first would reorder them.
			flush()
			kid, next := parseGroup(t, s, i)
			out.kids = append(out.kids, kid)
			i = next
		case '}':
			flush()
			return out, i + 1
		case ',':
			flush()
			i++
		default:
			tok.WriteByte(c)
			i++
		}
	}
	t.Fatal("unterminated initializer")
	return out, len(s)
}

func uints(t *testing.T, vals []string) []uint64 {
	t.Helper()
	out := make([]uint64, len(vals))
	for i, v := range vals {
		v = strings.TrimSpace(v)
		base, digits := 10, v
		if strings.HasPrefix(v, "0x") || strings.HasPrefix(v, "0X") {
			base, digits = 16, v[2:]
		}
		n, err := strconv.ParseUint(digits, base, 64)
		if err != nil {
			t.Fatalf("parse %q: %v", v, err)
		}
		out[i] = n
	}
	return out
}

// --- emitters --------------------------------------------------------------

func list(vals []uint64, perLine int, asHex bool) string {
	var b strings.Builder
	for i, v := range vals {
		if i%perLine == 0 {
			b.WriteString("\n\t")
		}
		if asHex {
			fmt.Fprintf(&b, "0x%x, ", v)
		} else {
			fmt.Fprintf(&b, "%d, ", v)
		}
	}
	b.WriteString("\n")
	return b.String()
}

func emitCoef(t *testing.T, wmadata string) string {
	var b strings.Builder
	b.WriteString(`
// The six coefficient books, three pairs of two. A book maps a VLC index to a
// run and a level: index 0 is the escape, index 1 is end-of-block, and every
// index above that names a (run, level). coefLevels is the ladder that
// expands them, entry k giving how many consecutive indices carry level k+1,
// counted from index 2 upward.

var coefCodes = [6][]uint32{`)
	for i := 0; i < 6; i++ {
		v := uints(t, initializer(t, wmadata, fmt.Sprintf("coef%d_huffcodes", i)).flat())
		fmt.Fprintf(&b, "\n\t{%s},", list(v, 12, true))
	}
	b.WriteString("\n}\n\nvar coefBits = [6][]uint8{")
	for i := 0; i < 6; i++ {
		v := uints(t, initializer(t, wmadata, fmt.Sprintf("coef%d_huffbits", i)).flat())
		fmt.Fprintf(&b, "\n\t{%s},", list(v, 24, false))
	}
	b.WriteString("\n}\n\nvar coefLevels = [6][]uint16{")
	for i := 0; i < 6; i++ {
		v := uints(t, initializer(t, wmadata, fmt.Sprintf("levels%d", i)).flat())
		fmt.Fprintf(&b, "\n\t{%s},", list(v, 16, false))
	}
	b.WriteString("\n}\n")
	return b.String()
}

func emitExp(t *testing.T, wmadata, aactab string) string {
	var b strings.Builder

	b.WriteString(`
// VLC-coded exponents (flags2 bit 0 set) are DPCM-coded with the AAC
// scalefactor book biased by -60: the same 121-entry book
// codec/aac/tables_hcb.go carries, duplicated here only because neither
// package imports the other.

var expScaleCodes = [121]uint32{`)
	code := uints(t, initializer(t, aactab, "ff_aac_scalefactor_code").flat())
	if len(code) != 121 {
		t.Fatalf("scalefactor code: %d entries", len(code))
	}
	b.WriteString(list(code, 8, true) + "}\n")

	b.WriteString("\nvar expScaleBits = [121]uint8{")
	bits := uints(t, initializer(t, aactab, "ff_aac_scalefactor_bits").flat())
	if len(bits) != 121 {
		t.Fatalf("scalefactor bits: %d entries", len(bits))
	}
	b.WriteString(list(bits, 20, false) + "}\n")

	b.WriteString(`
// hgainHuff is the noise-gain book as {symbol, length} pairs in canonical code
// order. The symbol is biased: the gain delta it stands for is symbol-18.

var hgainHuff = [37][2]uint8{`)
	for _, p := range initializer(t, wmadata, "ff_wma_hgain_hufftab").kids {
		v := uints(t, p.flat())
		fmt.Fprintf(&b, "\n\t{%d, %d},", v[0], v[1])
	}
	b.WriteString("\n}\n")

	b.WriteString(`
// lspCodebook holds the ten LSP coefficient rows read when exponents are LSP
// coded (flags2 bit 0 clear). Rows 0 and 8..9 are read with 3 bits and so use
// their first eight entries; the rest are read with 4 bits and use all
// sixteen. Row 5 entry 10 breaks that row's monotone descent and is
// reproduced as upstream has it, since matching deployed decoders is the
// whole point of the table (docs/notes/wma-bitstream.md, "The one entry that
// looks wrong").

var lspCodebook = [nbLSPCoefs][16]float32{`)
	rows := initializer(t, wmadata, "ff_wma_lsp_codebook")
	if len(rows.kids) != nbLSPCoefs {
		t.Fatalf("lsp codebook: %d rows", len(rows.kids))
	}
	for _, r := range rows.kids {
		b.WriteString("\n\t{")
		for i, v := range r.flat() {
			if i%4 == 0 {
				b.WriteString("\n\t\t")
			}
			fmt.Fprintf(&b, "%s, ", strings.TrimSpace(v))
		}
		b.WriteString("\n\t},")
	}
	b.WriteString("\n}\n")
	return b.String()
}

func emitBands(t *testing.T, wmadata, freqs string) string {
	var b strings.Builder

	b.WriteString(`
// criticalFreqs are the upper edges in Hz of the 25 critical bands the
// exponent bands are laid out on. Published psychoacoustic data (the Bark
// scale), not WMA-specific.

var criticalFreqs = [25]uint16{`)
	b.WriteString(list(uints(t, initializer(t, freqs, "ff_wma_critical_freqs").flat()), 8, false) + "}\n")

	b.WriteString(`
// The v2 exponent-band widths that are tabulated rather than computed, for the
// three shortest block sizes at 22.05 kHz and up. Upstream stores each row's
// band count as its first entry; that is dropped here, since a Go slice
// carries its own length. Row index is frameLenBits-7-k for block k.

`)
	for _, rate := range []int{22050, 32000, 44100} {
		fmt.Fprintf(&b, "var expBands%d = [3][]uint8{", rate)
		rows := initializer(t, wmadata, fmt.Sprintf("exponent_band_%d", rate)).kids
		if len(rows) != 3 {
			t.Fatalf("exponent_band_%d: %d rows, want 3", rate, len(rows))
		}
		for _, r := range rows {
			v := uints(t, r.flat())
			n := int(v[0])
			if len(v)-1 != n {
				t.Fatalf("exponent_band_%d: count %d, %d widths", rate, n, len(v)-1)
			}
			fmt.Fprintf(&b, "\n\t{%s},", list(v[1:], 16, false))
		}
		b.WriteString("\n}\n\n")
	}
	return b.String()
}
