// Code generated by tablesgen; DO NOT EDIT.
// Regenerate with `WAXFLOW_FFMPEG_SRC=... go generate ./codec/wma`.
//
// Black-box parameter artifact (ADR-0001): data only, no decoder logic. WMA
// has no published bitstream spec, so these are extracted from FFmpeg's data
// files, pinned by SHA-256 in tablesgen_test.go, rather than restated from a
// normative document. See THIRD-PARTY-NOTICES.md and docs/notes/wma-bitstream.md.

package wma

// criticalFreqs are the upper edges in Hz of the 25 critical bands the
// exponent bands are laid out on. Published psychoacoustic data (the Bark
// scale), not WMA-specific.

var criticalFreqs = [25]uint16{
	100, 200, 300, 400, 510, 630, 770, 920,
	1080, 1270, 1480, 1720, 2000, 2320, 2700, 3150,
	3700, 4400, 5300, 6400, 7700, 9500, 12000, 15500,
	24500,
}

// The v2 exponent-band widths that are tabulated rather than computed, for the
// three shortest block sizes at 22.05 kHz and up. Upstream stores each row's
// band count as its first entry; that is dropped here, since a Go slice
// carries its own length. Row index is frameLenBits-7-k for block k.

var expBands22050 = [3][]uint8{
	{
		4, 8, 4, 8, 8, 12, 20, 24, 24, 16,
	},
	{
		4, 8, 8, 4, 12, 12, 16, 24, 16, 20, 24, 32, 40, 36,
	},
	{
		4, 4, 4, 8, 4, 4, 8, 8, 8, 8, 8, 12, 12, 16, 16, 24,
		24, 32, 44, 48, 60, 84, 72,
	},
}

var expBands32000 = [3][]uint8{
	{
		4, 4, 8, 4, 4, 12, 16, 24, 20, 28, 4,
	},
	{
		4, 8, 4, 4, 8, 8, 16, 20, 12, 20, 20, 28, 40, 56, 8,
	},
	{
		8, 4, 8, 8, 12, 16, 20, 24, 40, 32, 32, 44, 56, 80, 112, 16,
	},
}

var expBands44100 = [3][]uint8{
	{
		4, 4, 4, 4, 4, 8, 8, 8, 12, 16, 20, 36,
	},
	{
		4, 8, 4, 8, 8, 4, 8, 8, 12, 12, 12, 24, 28, 40, 76,
	},
	{
		4, 8, 8, 4, 12, 12, 8, 8, 24, 16, 20, 24, 32, 40, 60, 80,
		152,
	},
}
