package waxflow_test

// Multichannel AAC decode. The fixtures are generated by ffmpeg at run
// time rather than committed, because the point of the identity test is
// which speaker each decoded channel belongs to, and that is only
// meaningful against a file whose per-channel content an independent
// encoder placed.

import (
	"bytes"
	"context"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"testing"

	"github.com/colespringer/waxflow"
	"github.com/colespringer/waxflow/audio"
	"github.com/colespringer/waxflow/container"
	"github.com/colespringer/waxflow/internal/testutil"
)

// mcLayout is one AAC channel configuration under test: ffmpeg's name for
// the layout, its channels in ffmpeg's order, and the mask we must report.
// ffmpeg orders a layout's channels by ascending WAVE mask bit, the same
// order audio.ChannelMask uses, so chans[i] is the speaker our output
// channel i must hold.
type mcLayout struct {
	config int      // channelConfiguration in the AudioSpecificConfig
	name   string   // ffmpeg channel layout name
	chans  []string // ffmpeg channel names, in order
	want   audio.ChannelMask
}

// mcLayouts covers every configuration the decoder claims. Configuration 7
// is absent because the decoder refuses it; TestAACConfig7Refused pins
// that, so this list going quiet is not how support would disappear.
var mcLayouts = []mcLayout{
	{3, "3.0", []string{"FL", "FR", "FC"},
		audio.FrontLeft | audio.FrontRight | audio.FrontCenter},
	{4, "4.0", []string{"FL", "FR", "FC", "BC"},
		audio.FrontLeft | audio.FrontRight | audio.FrontCenter | audio.BackCenter},
	{5, "5.0", []string{"FL", "FR", "FC", "BL", "BR"},
		audio.FrontLeft | audio.FrontRight | audio.FrontCenter | audio.BackLeft | audio.BackRight},
	{6, "5.1", []string{"FL", "FR", "FC", "LFE", "BL", "BR"},
		audio.FrontLeft | audio.FrontRight | audio.FrontCenter | audio.LowFrequency |
			audio.BackLeft | audio.BackRight},
}

// mc51 is the configuration the WaxTap report needs, and the one the
// single-layout tests below use.
var mc51 = mcLayouts[3]

// tone is the frequency channel c carries in a generated fixture, spaced
// far enough apart that a Goertzel bin cannot confuse two of them. The LFE
// gets a low one: an encoder band-limits that channel, so a tone up with
// the others would be filtered away and read as a dead channel.
func (l mcLayout) tone(c int) float64 {
	if l.chans[c] == "LFE" {
		return 60
	}
	return 300 + 250*float64(c)
}

// mcFixture writes an AAC file whose every channel carries its own tone,
// in an MP4 or, with ext "aac", a raw ADTS stream. The join filter's
// mapping is spelled out rather than left to its default, which assigns by
// channel name and so would put the first mono input (whose own layout is
// a lone FC) into the output's centre.
//
// Fixtures are memoized per layout and extension: four of the tests below
// want the same 5.1 file, and generating it once is a second of ffmpeg
// saved on every run. mcDir outlives any one test, so the path stays
// readable for the whole package.
func mcFixture(t *testing.T, l mcLayout, ext string) string {
	t.Helper()
	testutil.FFmpeg(t) // take the skip here, before the memo hides it
	key := l.name + "." + ext
	path, err := mcFixtures.byKey(key, func() (string, error) {
		n := len(l.chans)
		args := []string{"-v", "error", "-y"}
		var labels, maps []string
		for i := range n {
			args = append(args, "-f", "lavfi", "-i",
				fmt.Sprintf("sine=frequency=%g:duration=1:sample_rate=48000", l.tone(i)))
			labels = append(labels, fmt.Sprintf("[%d:a]", i))
			maps = append(maps, fmt.Sprintf("%d.0-%s", i, l.chans[i]))
		}
		args = append(args, "-filter_complex", strings.Join(labels, "")+
			"join=inputs="+strconv.Itoa(n)+":channel_layout="+l.name+
			":map="+strings.Join(maps, "|")+"[a]",
			"-map", "[a]", "-c:a", "aac", "-b:a", "384k")
		if ext == "aac" {
			args = append(args, "-f", "adts")
		}
		dir, err := mcFixtures.dir()
		if err != nil {
			return "", err
		}
		out := filepath.Join(dir, key)
		args = append(args, out)
		if msg, err := exec.Command(testutil.FFmpeg(t), args...).CombinedOutput(); err != nil {
			return "", fmt.Errorf("generating the %s fixture: %w\n%s", key, err, msg)
		}
		return out, nil
	})
	if err != nil {
		t.Fatal(err)
	}
	return path
}

// TestMain removes the shared fixture directory. It exists only for that:
// a t.TempDir would be cleaned when whichever test asked for it first
// finished, taking the memo's files with it.
func TestMain(m *testing.M) {
	code := m.Run()
	mcFixtures.cleanup()
	os.Exit(code)
}

// mcFixtures memoizes generated fixtures across the package's tests. The
// directory is created on first use and removed by TestMain, since a
// t.TempDir would go with whichever test happened to ask first.
var mcFixtures fixtureCache

type fixtureCache struct {
	mu    sync.Mutex
	root  string
	paths map[string]string
}

func (c *fixtureCache) dir() (string, error) {
	if c.root == "" {
		d, err := os.MkdirTemp("", "waxflow-mc")
		if err != nil {
			return "", err
		}
		c.root = d
	}
	return c.root, nil
}

func (c *fixtureCache) byKey(key string, gen func() (string, error)) (string, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	if p, ok := c.paths[key]; ok {
		return p, nil
	}
	p, err := gen()
	if err != nil {
		return "", err
	}
	if c.paths == nil {
		c.paths = map[string]string{}
	}
	c.paths[key] = p
	return p, nil
}

func (c *fixtureCache) cleanup() {
	if c.root != "" {
		os.RemoveAll(c.root)
	}
}

// fileSource reads a generated fixture off disk.
func fileSource(t *testing.T, path string) container.Source {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return container.BytesSource(raw)
}

// decodeStream reads a source of unknown declared length (raw ADTS
// declares none) into planar float channels.
func decodeStream(t *testing.T, src container.Source, hint string) ([][]float32, audio.Format) {
	t.Helper()
	med, err := waxflow.New().OpenStream(src, hint)
	if err != nil {
		t.Fatal(err)
	}
	defer med.Close()
	f := med.Info().Default().Fmt
	tmp := audio.Get(f, audio.StandardChunk)
	defer audio.Put(tmp)
	out := make([][]float32, f.Channels)
	for {
		err := med.ReadChunk(tmp)
		if errors.Is(err, io.EOF) {
			return out, f
		}
		if err != nil {
			t.Fatal(err)
		}
		for c := range out {
			out[c] = append(out[c], tmp.ChanF(c)...)
		}
	}
}

// chanFloat returns channel c as float32 whatever domain the buffer is
// in, so one comparison works for a float decode and an integer one.
func chanFloat(b *audio.Buffer, c int) []float32 {
	if b.F != nil {
		return b.ChanF(c)
	}
	src := b.ChanI(c)
	scale := float32(1) / float32(int64(1)<<(b.Fmt.BitDepth-1))
	out := make([]float32, len(src))
	for i, v := range src {
		out[i] = float32(v) * scale
	}
	return out
}

// goertzel is the magnitude of freq in x, normalized so a full-scale sine
// reads about 0.5.
func goertzel(x []float32, rate int, freq float64) float64 {
	w := 2 * math.Pi * freq / float64(rate)
	coeff := 2 * math.Cos(w)
	var s1, s2 float64
	for _, v := range x {
		s := float64(v) + coeff*s1 - s2
		s2, s1 = s1, s
	}
	re := s1 - s2*math.Cos(w)
	im := s2 * math.Sin(w)
	return math.Hypot(re, im) / float64(len(x))
}

// TestAACMultichannelChannelIdentity is the test the remap needs, because
// a wrong element-to-speaker map fails silently: the file decodes, at full
// length, with every channel present -- just not the one it should be. It
// asserts per channel that the tone that channel was built with dominates
// every other channel's tone.
func TestAACMultichannelChannelIdentity(t *testing.T) {
	for _, l := range mcLayouts {
		t.Run(l.name, func(t *testing.T) {
			buf := decodeAll(t, fileSource(t, mcFixture(t, l, "m4a")), "m4a")
			n := len(l.chans)
			if buf.Fmt.Channels != n {
				t.Fatalf("decoded %d channels, want %d", buf.Fmt.Channels, n)
			}
			if buf.Fmt.Layout != l.want {
				t.Errorf("layout = %v, want %v", buf.Fmt.Layout, l.want)
			}
			for c := range n {
				ch := chanFloat(buf, c)
				own := goertzel(ch, buf.Fmt.Rate, l.tone(c))
				// The floor comes first: a channel that decoded to silence
				// would pass the dominance check below against every other
				// tone at zero, and report as a mapping error rather than as
				// the missing channel it is.
				if own < 0.02 {
					t.Errorf("channel %d (%s) has only %.4f at its own %g Hz, want a real tone",
						c, l.chans[c], own, l.tone(c))
					continue
				}
				for other := range n {
					if other == c || l.tone(other) == l.tone(c) {
						continue
					}
					if got := goertzel(ch, buf.Fmt.Rate, l.tone(other)); got >= own {
						t.Errorf("channel %d (%s) carries %s's %g Hz at %.4f, above its own %g Hz at %.4f: "+
							"the element-to-speaker map is wrong",
							c, l.chans[c], l.chans[other], l.tone(other), got, l.tone(c), own)
					}
				}
			}
		})
	}
}

// TestAACMultichannelProbeUsesASC pins where the channel count comes
// from. A multichannel mp4a's stsd sample entry conventionally says 2 no
// matter the real count, which is the classic multichannel-MP4 trap, so
// the trap is written into the fixture rather than hoped for: the sample
// entry is rewritten to claim stereo and the probe must still report the
// ASC's six.
func TestAACMultichannelProbeUsesASC(t *testing.T) {
	raw, err := os.ReadFile(mcFixture(t, mc51, "m4a"))
	if err != nil {
		t.Fatal(err)
	}
	if n := bytes.Count(raw, []byte("mp4a")); n != 1 {
		t.Fatalf("found %d mp4a markers, want exactly 1 to patch", n)
	}
	// From the 4-byte sample entry type: SampleEntry reserved(6) and
	// data_reference_index(2), then AudioSampleEntry version(2)
	// revision(2) vendor(4), putting channelcount at +20.
	off := bytes.Index(raw, []byte("mp4a")) + 20
	was := binary.BigEndian.Uint16(raw[off:])
	binary.BigEndian.PutUint16(raw[off:], 2)

	info, err := waxflow.New().Probe(container.BytesSource(raw), "m4a", nil)
	if err != nil {
		t.Fatalf("Probe: %v", err)
	}
	tr := info.Default()
	if tr.Fmt.Channels != 6 {
		t.Errorf("probe reports %d channels with the sample entry claiming 2 (it held %d); "+
			"want the ASC's 6", tr.Fmt.Channels, was)
	}
	if tr.Fmt.Layout != mc51.want {
		t.Errorf("probe layout = %v, want %v", tr.Fmt.Layout, mc51.want)
	}
}

// TestAACMultichannelDifferential decodes a 5.1 file with both our decoder
// and ffmpeg's and compares per channel, which catches a remap that is
// self-consistent but disagrees with every other decoder.
func TestAACMultichannelDifferential(t *testing.T) {
	path := mcFixture(t, mc51, "m4a")
	ours := decodeAll(t, fileSource(t, path), "m4a")
	theirs := testutil.FFmpegDecodeF32(t, path)

	n := len(mc51.chans)
	frames := min(len(theirs)/n, ours.N)
	if frames == 0 {
		t.Fatal("ffmpeg decoded nothing")
	}
	for c := range n {
		ref := make([]float32, frames)
		for i := range ref {
			ref[i] = theirs[i*n+c]
		}
		got := goertzel(chanFloat(ours, c)[:frames], ours.Fmt.Rate, mc51.tone(c))
		want := goertzel(ref, ours.Fmt.Rate, mc51.tone(c))
		if math.Abs(got-want) > 0.01 {
			t.Errorf("channel %d (%s) at %g Hz: ours %.4f, ffmpeg %.4f",
				c, mc51.chans[c], mc51.tone(c), got, want)
		}
	}
}

// TestAACMultichannelDownmix runs 5.1 through the engine to stereo, which
// is what an explicit channel count exists for and the path most callers
// asking for a multichannel source will take.
func TestAACMultichannelDownmix(t *testing.T) {
	path := mcFixture(t, mc51, "m4a")

	var out bytes.Buffer
	if _, err := waxflow.New().Transcode(context.Background(), fileSource(t, path), "m4a", &out,
		waxflow.TranscodeOptions{Format: "wav", Channels: 2}); err != nil {
		t.Fatalf("5.1 to stereo: %v", err)
	}
	buf := decodeAll(t, container.BytesSource(out.Bytes()), "wav")
	if buf.Fmt.Channels != 2 {
		t.Fatalf("downmix produced %d channels, want 2", buf.Fmt.Channels)
	}
	// The front-left tone belongs mostly in the left output and the
	// front-right tone mostly in the right. A downmix fed a wrong remap
	// would put the surrounds or the centre there instead, and the centre
	// is the one that would look plausible: it lands equally in both.
	left, right := chanFloat(buf, 0), chanFloat(buf, 1)
	rate := buf.Fmt.Rate
	for _, tc := range []struct {
		name       string
		freq       float64
		near, away []float32
	}{
		{"front left", mc51.tone(0), left, right},
		{"front right", mc51.tone(1), right, left},
	} {
		n, a := goertzel(tc.near, rate, tc.freq), goertzel(tc.away, rate, tc.freq)
		if n <= a {
			t.Errorf("%s tone reads %.4f in its own channel and %.4f in the other; want it dominant",
				tc.name, n, a)
		}
	}
}

// TestAACMultichannelADTS confirms the raw-ADTS path follows for free.
// The ADTS header carries the same 3-bit channel_configuration, which
// adts synthesizes into an ASC and hands to the same ParseASC, so nothing
// there needed changing -- but "nothing needed changing" is a claim worth
// a test rather than a comment.
func TestAACMultichannelADTS(t *testing.T) {
	path := mcFixture(t, mc51, "aac")
	chans, f := decodeStream(t, fileSource(t, path), "aac")
	if f.Channels != 6 {
		t.Fatalf("ADTS decode has %d channels, want 6", f.Channels)
	}
	if f.Layout != mc51.want {
		t.Errorf("ADTS layout = %v, want %v", f.Layout, mc51.want)
	}
	for c := range 6 {
		if own := goertzel(chans[c], f.Rate, mc51.tone(c)); own < 0.02 {
			t.Errorf("ADTS channel %d (%s) has %.4f at its own %g Hz",
				c, mc51.chans[c], own, mc51.tone(c))
		}
	}
}

// TestAACConfig7Refused pins the one configuration in 1-7 that is not
// shipped, against files a real encoder produced.
//
// The refusal is not a gap waiting to be filled in. ISO/IEC 14496-3
// Table 1.19 makes configuration 7 a 7.1 whose extra pair is at the FRONT
// (Lc/Rc); ffmpeg writes that same configuration for its own 7.1, whose
// extra pair is at the SIDE, and reads it back that way. Implementing
// either reading decodes the other's files into the wrong speakers at
// full length and full loudness -- precisely the silent failure the
// channel map exists to prevent -- so the stream is refused by name until
// something settles which reading a file means.
//
// Only the older ffmpeg builds write configuration 7 for a side-pair 7.1.
// Newer ones signal it as 12, which ADTS's 3-bit field cannot hold at all, so
// there is no fixture to be had on those and this test skips. The refusal
// itself is pinned without an encoder in codec/aac.
func TestAACConfig7Refused(t *testing.T) {
	dir := t.TempDir()
	ffmpeg := testutil.FFmpeg(t)
	run := func(name string, args ...string) (string, error) {
		path := filepath.Join(dir, name)
		out, err := exec.Command(ffmpeg, append(args, path)...).CombinedOutput()
		if err != nil {
			return "", fmt.Errorf("%w\n%s", err, out)
		}
		return path, nil
	}
	// The MP4 is the encode and the ADTS is that same stream copied out of it,
	// so the pair carries one encoder decision instead of two that have to be
	// assumed equal. It is also the order that keeps the two failures apart:
	// anything wrong with the arguments themselves fails here, where it cannot
	// be mistaken for the configuration skip below.
	m4a, err := run("7.1.m4a", "-v", "error", "-y",
		"-f", "lavfi", "-i", "sine=frequency=300:duration=1:sample_rate=48000",
		"-af", "pan=7.1|FL=c0|FR=c0|FC=c0|LFE=c0|BL=c0|BR=c0|SL=c0|SR=c0",
		"-c:a", "aac", "-b:a", "448k")
	if err != nil {
		t.Fatalf("generating 7.1.m4a: %v", err)
	}
	// Newer ffmpeg signals this layout as configuration 12, which ADTS's
	// 3-bit field cannot hold, so the copy is refused outright and the build
	// has no configuration 7 to offer at all.
	adts, err := run("7.1.aac", "-v", "error", "-y", "-i", m4a, "-c", "copy", "-f", "adts")
	if err != nil {
		t.Skipf("this ffmpeg will not write its 7.1 as ADTS, so it has no "+
			"configuration 7 to refuse: %v", err)
	}

	// Guard the premise. An ffmpeg that stops writing configuration 7 for
	// this layout leaves fixtures that no longer exercise the refusal, and
	// the test would go green for the wrong reason, so it skips instead. The
	// ADTS header carries the field in the clear, where the MP4 buries it in
	// an esds descriptor chain; the two are one stream, so reading it here
	// covers both files.
	raw, err := os.ReadFile(adts)
	if err != nil {
		t.Fatal(err)
	}
	if len(raw) < 4 || raw[0] != 0xFF || raw[1]&0xF0 != 0xF0 {
		t.Fatal("fixture is not an ADTS stream")
	}
	// syncword(12) id(1) layer(2) protection_absent(1) profile(2)
	// sampling_frequency_index(4) private(1) channel_configuration(3)
	if got := int(raw[2]&1)<<2 | int(raw[3]>>6); got != 7 {
		t.Skipf("this ffmpeg declares channel configuration %d for its 7.1, not 7", got)
	}

	for _, tc := range []struct{ path, hint string }{{adts, "aac"}, {m4a, "m4a"}} {
		_, err := waxflow.New().Probe(fileSource(t, tc.path), tc.hint, nil)
		if err == nil {
			t.Errorf("%s: a channel configuration 7 stream was accepted", tc.hint)
			continue
		}
		if !strings.Contains(err.Error(), "channel configuration 7") {
			t.Errorf("%s: error = %q, want it to name channel configuration 7", tc.hint, err)
		}
	}
}

// TestAACMultichannelToLossless pins the other end of the pipeline: a
// decoded multichannel source has to survive an encode, not just decode.
//
// Every configuration runs, because the outcome is not the same for all
// of them and testing only 5.1 hid that. FLAC fixes the speaker
// assignment per channel count, and its four-channel assignment is quad
// (FL FR BL BR). AAC's configuration 4 is a centre and a back centre, a
// layout FLAC has no way to name, so it is refused -- correctly, but the
// refusal has to say so, since audio.Format.String does not print the
// layout and the message would otherwise name two identical formats.
// WAV carries an explicit mask and takes all four.
func TestAACMultichannelToLossless(t *testing.T) {
	for _, l := range mcLayouts {
		t.Run(l.name, func(t *testing.T) {
			src := fileSource(t, mcFixture(t, l, "m4a"))
			n := len(l.chans)

			// WAV states the mask outright, so every layout round-trips.
			var wav bytes.Buffer
			if _, err := waxflow.New().Transcode(context.Background(), src, "m4a", &wav,
				waxflow.TranscodeOptions{Format: "wav"}); err != nil {
				t.Fatalf("%s to wav: %v", l.name, err)
			}
			buf := decodeAll(t, container.BytesSource(wav.Bytes()), "wav")
			if buf.Fmt.Channels != n || buf.Fmt.Layout != l.want {
				t.Errorf("wav output is %d ch %v, want %d ch %v",
					buf.Fmt.Channels, buf.Fmt.Layout, n, l.want)
			}

			var flac bytes.Buffer
			_, err := waxflow.New().Transcode(context.Background(), fileSource(t, mcFixture(t, l, "m4a")),
				"m4a", &flac, waxflow.TranscodeOptions{Format: "flac"})
			if l.want != audio.DefaultLayout(n) {
				// The FLAC assignment for this count is a different set of
				// speakers, so there is nowhere to put this layout.
				if err == nil {
					t.Fatalf("%s encoded to flac, whose %d-channel assignment is %v",
						l.name, n, audio.DefaultLayout(n))
				}
				for _, want := range []string{l.want.String(), audio.DefaultLayout(n).String()} {
					if !strings.Contains(err.Error(), want) {
						t.Errorf("%s to flac: error = %q, want it to name %q", l.name, err, want)
					}
				}
				return
			}
			if err != nil {
				t.Fatalf("%s to flac: %v", l.name, err)
			}
			buf = decodeAll(t, container.BytesSource(flac.Bytes()), "flac")
			if buf.Fmt.Channels != n || buf.Fmt.Layout != l.want {
				t.Fatalf("flac output is %d ch %v, want %d ch %v",
					buf.Fmt.Channels, buf.Fmt.Layout, n, l.want)
			}
			for c := range n {
				if own := goertzel(chanFloat(buf, c), buf.Fmt.Rate, l.tone(c)); own < 0.02 {
					t.Errorf("flac channel %d (%s) has %.4f at its own %g Hz",
						c, l.chans[c], own, l.tone(c))
				}
			}
		})
	}
}
