//go:build wmaprotablesgen

package wmapro

// Offline extraction of the WMA Pro parameter tables (ADR-0001). Run with:
//
//	WAXFLOW_FFMPEG_SRC=/path/to/ffmpeg/libavcodec go generate ./codec/wmapro
//
// which is wired to `go test -tags wmaprotablesgen -run ^TestGenerateTables$`.
//
// WMA Pro, like WMA v1 and v2, has no published bitstream spec, so its tables
// cannot be restated from a normative document the way the AAC and SBR tables
// are. They are extracted instead, mechanically and under a SHA-256 pin, from
// FFmpeg's data file, in the analysis pass ADR-0001 separates from
// implementation. Mechanically matters: three thousand numbers cannot be
// transcribed by hand and then be trusted, and a reviewer can re-run this
// against the pinned upstream and diff the result.
//
// The pinned file is data, not logic. wmaprodata.h holds the two scale-factor
// books, the two run-level coefficient books, the three vector books, the
// scale-factor band edges and the default channel decorrelation matrices.
// Which book the stream selects, and the symbol biases each is read with, are
// rules rather than data and live in docs/notes/wma-pro-bitstream.md.

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

// Pinned upstream: FFmpeg n9.0, commit d32b387f2b0a484599d4587d651891f0c63c4238.
// A changed digest fails loudly rather than silently regenerating different
// tables, the discipline internal/testutil.Vectors uses for fetched vectors.
var pinned = map[string]string{
	"wmaprodata.h": "0ecb9a82befb7409d379e759c8bcf613c7958cd8cac698278a1427ab7b1ef29f",
}

func TestGenerateTables(t *testing.T) {
	dir := os.Getenv("WAXFLOW_FFMPEG_SRC")
	if dir == "" {
		t.Fatal("set WAXFLOW_FFMPEG_SRC to a checked-out ffmpeg libavcodec/ directory")
	}
	src := map[string]string{}
	for name, want := range pinned {
		b, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			t.Fatalf("read %s: %v", name, err)
		}
		b = bytes.ReplaceAll(b, []byte("\r\n"), []byte("\n"))
		// An empty pin prints the digest it would need, which is how a new
		// upstream file gets pinned in the first place.
		if got := hex.EncodeToString(sha256Sum(b)); got != want {
			t.Fatalf("%s: digest %s, pinned %q", name, got, want)
		}
		src[name] = string(b)
	}

	data := src["wmaprodata.h"]
	writeFile(t, "tables_bands.go", emitBands(t, data))
	writeFile(t, "tables_scale.go", emitScale(t, data))
	writeFile(t, "tables_coef.go", emitCoef(t, data))
	writeFile(t, "tables_decorr.go", emitDecorr(t, data))
}

func sha256Sum(b []byte) []byte { s := sha256.Sum256(b); return s[:] }

const genHeader = "// Code generated by tablesgen; DO NOT EDIT.\n" +
	"// Regenerate with `WAXFLOW_FFMPEG_SRC=... go generate ./codec/wmapro`.\n" +
	"//\n" +
	"// Black-box parameter artifact (ADR-0001): data only, no decoder logic. WMA\n" +
	"// Pro has no published bitstream spec, so these are extracted from FFmpeg's\n" +
	"// data file, pinned by SHA-256 in tablesgen_test.go, rather than restated from\n" +
	"// a normative document. See THIRD-PARTY-NOTICES.md and\n" +
	"// docs/notes/wma-pro-bitstream.md.\n" +
	"\n" +
	"package wmapro\n"

func writeFile(t *testing.T, name, body string) {
	t.Helper()
	out, err := format.Source([]byte(genHeader + body))
	if err != nil {
		t.Fatalf("%s: gofmt: %v", name, err)
	}
	if err := os.WriteFile(name, out, 0o644); err != nil {
		t.Fatal(err)
	}
	t.Logf("wrote %s (%d bytes)", name, len(out))
}

// --- C initializer parsing -------------------------------------------------

// node is one parsed C initializer: a scalar when kids is nil, otherwise a
// brace group. The tables here nest at most two deep.
type node struct {
	val  string
	kids []node
}

func (n node) flat() []string {
	if n.kids == nil {
		return []string{n.val}
	}
	var out []string
	for _, k := range n.kids {
		out = append(out, k.flat()...)
	}
	return out
}

// initializer returns the brace group of the named C array. Comments come off
// before the search, so a name mentioned in prose ahead of its declaration
// cannot capture it, and the match needs a non-identifier character to its
// left, so `vec1_table` does not latch onto a longer name ending in it. Both
// would otherwise parse the wrong array and still compile.
func initializer(t *testing.T, src, name string) node {
	t.Helper()
	src = stripComments(src)
	at := -1
	for i := 0; ; {
		j := strings.Index(src[i:], name+"[")
		if j < 0 {
			break
		}
		j += i
		if j == 0 || !isIdentByte(src[j-1]) {
			at = j
			break
		}
		i = j + 1
	}
	if at < 0 {
		t.Fatalf("%s: no declaration found", name)
	}
	j := strings.IndexByte(src[at:], '{')
	if j < 0 {
		t.Fatalf("%s: no initializer", name)
	}
	body, _ := parseGroup(t, src[at+j:], 0)
	return body
}

func isIdentByte(c byte) bool {
	return c == '_' || c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9'
}

func stripComments(s string) string {
	var b strings.Builder
	for i := 0; i < len(s); {
		switch {
		case strings.HasPrefix(s[i:], "/*"):
			e := strings.Index(s[i+2:], "*/")
			if e < 0 {
				return b.String()
			}
			i += 2 + e + 2
		case strings.HasPrefix(s[i:], "//"):
			e := strings.IndexByte(s[i:], '\n')
			if e < 0 {
				return b.String()
			}
			i += e
		default:
			b.WriteByte(s[i])
			i++
		}
	}
	return b.String()
}

// parseGroup consumes the brace group starting at s[at] and returns it plus
// the index just past its closing brace.
func parseGroup(t *testing.T, s string, at int) (node, int) {
	t.Helper()
	if s[at] != '{' {
		t.Fatalf("expected a brace group at %d", at)
	}
	out := node{kids: []node{}}
	var tok strings.Builder
	flush := func() {
		v := strings.TrimSpace(tok.String())
		tok.Reset()
		if v != "" {
			out.kids = append(out.kids, node{val: v})
		}
	}
	for i := at + 1; i < len(s); {
		switch c := s[i]; c {
		case '{':
			// Flush first: a scalar sitting before a nested group belongs
			// ahead of it, and appending the group first would reorder them.
			flush()
			kid, next := parseGroup(t, s, i)
			out.kids = append(out.kids, kid)
			i = next
		case '}':
			flush()
			return out, i + 1
		case ',':
			flush()
			i++
		default:
			tok.WriteByte(c)
			i++
		}
	}
	t.Fatal("unterminated initializer")
	return out, len(s)
}

func uints(t *testing.T, vals []string) []uint64 {
	t.Helper()
	out := make([]uint64, len(vals))
	for i, v := range vals {
		v = strings.TrimSpace(v)
		base, digits := 10, v
		if strings.HasPrefix(v, "0x") || strings.HasPrefix(v, "0X") {
			base, digits = 16, v[2:]
		}
		n, err := strconv.ParseUint(digits, base, 64)
		if err != nil {
			t.Fatalf("parse %q: %v", v, err)
		}
		out[i] = n
	}
	return out
}

// define returns the value of a C object-like #define. The book sizes and
// maximum code lengths are only read to check the parse, never emitted.
func define(t *testing.T, src, name string) int {
	t.Helper()
	for _, ln := range strings.Split(src, "\n") {
		f := strings.Fields(ln)
		if len(f) == 3 && f[0] == "#define" && f[1] == name {
			n, err := strconv.Atoi(f[2])
			if err != nil {
				t.Fatalf("#define %s: %v", name, err)
			}
			return n
		}
	}
	t.Fatalf("#define %s: not found", name)
	return 0
}

// --- Huffman books ---------------------------------------------------------

// book is one Huffman table in the shape a Go decoder wants it: parallel
// symbol and code-length arrays in canonical code order. Upstream stores some
// books as {symbol, length} rows and others as two arrays; only the container
// differs, so both land here.
type book struct {
	syms, lens []uint64
}

// pairBook reads a C [n][2] table whose rows are {symbol, length}.
func pairBook(t *testing.T, src, name string, n int) book {
	t.Helper()
	rows := initializer(t, src, name).kids
	if len(rows) != n {
		t.Fatalf("%s: %d rows, want %d", name, len(rows), n)
	}
	var b book
	for _, r := range rows {
		v := uints(t, r.flat())
		if len(v) != 2 {
			t.Fatalf("%s: row of %d values, want 2", name, len(v))
		}
		b.syms = append(b.syms, v[0])
		b.lens = append(b.lens, v[1])
	}
	return b
}

// splitBook reads a book upstream keeps as two parallel arrays.
func splitBook(t *testing.T, src, lensName, symsName string, n int) book {
	t.Helper()
	b := book{
		lens: uints(t, initializer(t, src, lensName).flat()),
		syms: uints(t, initializer(t, src, symsName).flat()),
	}
	if len(b.lens) != n || len(b.syms) != n {
		t.Fatalf("%s/%s: %d/%d entries, want %d", lensName, symsName, len(b.lens), len(b.syms), n)
	}
	return b
}

// check confirms the longest code matches the maximum upstream declares, which
// catches a parse that latched onto the wrong array.
func (b book) check(t *testing.T, name string, maxBits int) book {
	t.Helper()
	got := uint64(0)
	for _, l := range b.lens {
		if l > got {
			got = l
		}
	}
	if int(got) != maxBits {
		t.Fatalf("%s: longest code %d bits, upstream declares %d", name, got, maxBits)
	}
	for _, s := range b.syms {
		if s > 0xffff {
			t.Fatalf("%s: symbol %d does not fit uint16", name, s)
		}
	}
	return b
}

func (b book) emit(w *strings.Builder, name string) {
	fmt.Fprintf(w, "\nvar %sLens = [%d]uint8{%s}\n", name, len(b.lens), list(b.lens, 24, false))
	fmt.Fprintf(w, "\nvar %sSyms = [%d]uint16{%s}\n", name, len(b.syms), list(b.syms, 12, false))
}

// --- emitters --------------------------------------------------------------

func list(vals []uint64, perLine int, asHex bool) string {
	var b strings.Builder
	for i, v := range vals {
		if i%perLine == 0 {
			b.WriteString("\n\t")
		}
		if asHex {
			fmt.Fprintf(&b, "0x%x, ", v)
		} else {
			fmt.Fprintf(&b, "%d, ", v)
		}
	}
	b.WriteString("\n")
	return b.String()
}

// listRaw emits the C literals unchanged, for the float tables.
func listRaw(vals []string, perLine int) string {
	var b strings.Builder
	for i, v := range vals {
		if i%perLine == 0 {
			b.WriteString("\n\t")
		}
		fmt.Fprintf(&b, "%s, ", strings.TrimSpace(v))
	}
	b.WriteString("\n")
	return b.String()
}

func emitBands(t *testing.T, data string) string {
	var b strings.Builder
	b.WriteString(`
// bandEdgeFreqs are the upper edges in Hz that the scale-factor bands are laid
// out on, one band per edge that lands past the previous one. The band table
// is computed per block size from these and the sample rate rather than
// tabulated (docs/notes/wma-pro-bitstream.md).

`)
	v := uints(t, initializer(t, data, "critical_freq").flat())
	fmt.Fprintf(&b, "var bandEdgeFreqs = [%d]uint16{%s}\n", len(v), list(v, 7, false))
	return b.String()
}

func emitScale(t *testing.T, data string) string {
	var b strings.Builder

	b.WriteString(`
// The DPCM scale-factor book. Symbols are biased: the delta a symbol stands
// for is symbol-60.

`)
	n := define(t, data, "HUFF_SCALE_SIZE")
	pairBook(t, data, "scale_table", n).
		check(t, "scale_table", define(t, data, "HUFF_SCALE_MAXBITS")).
		emit(&b, "scaleDelta")

	b.WriteString(`
// The run-level scale-factor book, used when a subframe re-sends scale factors
// as deltas against the previous ones. A symbol names a (run, level) pair
// through the two tables below it.

`)
	n = define(t, data, "HUFF_SCALE_RL_SIZE")
	pairBook(t, data, "scale_rl_table", n).
		check(t, "scale_rl_table", define(t, data, "HUFF_SCALE_RL_MAXBITS")).
		emit(&b, "scaleRunLevel")

	runs := uints(t, initializer(t, data, "scale_rl_run").flat())
	levels := uints(t, initializer(t, data, "scale_rl_level").flat())
	if len(runs) != n || len(levels) != n {
		t.Fatalf("scale_rl run/level: %d/%d entries, want %d", len(runs), len(levels), n)
	}
	fmt.Fprintf(&b, "\nvar scaleRunLevelRuns = [%d]uint8{%s}\n", n, list(runs, 24, false))
	fmt.Fprintf(&b, "\nvar scaleRunLevelLevels = [%d]uint8{%s}\n", n, list(levels, 24, false))
	return b.String()
}

func emitCoef(t *testing.T, data string) string {
	var b strings.Builder

	sizes := [2]int{define(t, data, "HUFF_COEF0_SIZE"), define(t, data, "HUFF_COEF1_SIZE")}
	maxes := [2]int{define(t, data, "HUFF_COEF0_MAXBITS"), define(t, data, "HUFF_COEF1_MAXBITS")}
	books := [2]book{
		splitBook(t, data, "coef0_lens", "coef0_syms", sizes[0]).check(t, "coef0", maxes[0]),
		pairBook(t, data, "coef1_table", sizes[1]).check(t, "coef1", maxes[1]),
	}

	b.WriteString(`
// The two run-level coefficient books, selected by one bit at the top of the
// coefficient block. A symbol names a (run, level) pair through coefRuns and
// coefLevels; the last symbol of each book is the escape.

var coefLens = [2][]uint8{`)
	for _, bk := range books {
		fmt.Fprintf(&b, "\n\t{%s},", list(bk.lens, 24, false))
	}
	b.WriteString("\n}\n\nvar coefSyms = [2][]uint16{")
	for _, bk := range books {
		fmt.Fprintf(&b, "\n\t{%s},", list(bk.syms, 12, false))
	}

	b.WriteString("\n}\n\nvar coefRuns = [2][]uint16{")
	for i, name := range [2]string{"coef0_run", "coef1_run"} {
		v := uints(t, initializer(t, data, name).flat())
		if len(v) != sizes[i] {
			t.Fatalf("%s: %d entries, want %d", name, len(v), sizes[i])
		}
		fmt.Fprintf(&b, "\n\t{%s},", list(v, 16, false))
	}

	// Upstream stores the levels as float only to skip a conversion in its
	// inner loop. The literals are copied through unchanged.
	b.WriteString("\n}\n\nvar coefLevels = [2][]float32{")
	for i, name := range [2]string{"coef0_level", "coef1_level"} {
		v := initializer(t, data, name).flat()
		if len(v) != sizes[i] {
			t.Fatalf("%s: %d entries, want %d", name, len(v), sizes[i])
		}
		fmt.Fprintf(&b, "\n\t{%s},", listRaw(v, 16))
	}
	b.WriteString("\n}\n")

	b.WriteString(`
// The vector books, tried widest first. A vec4 symbol carries four
// coefficients in the nibbles of symbol-1, a vec2 symbol two, and a vec1
// symbol one value outright. Symbol 0 of the vec4 and vec2 books escapes to
// the narrower book; the last vec1 symbol escapes to an explicit value.

`)
	splitBook(t, data, "vec4_lens", "vec4_syms", define(t, data, "HUFF_VEC4_SIZE")).
		check(t, "vec4", define(t, data, "HUFF_VEC4_MAXBITS")).
		emit(&b, "vec4")
	pairBook(t, data, "vec2_table", define(t, data, "HUFF_VEC2_SIZE")).
		check(t, "vec2", define(t, data, "HUFF_VEC2_MAXBITS")).
		emit(&b, "vec2")
	pairBook(t, data, "vec1_table", define(t, data, "HUFF_VEC1_SIZE")).
		check(t, "vec1", define(t, data, "HUFF_VEC1_MAXBITS")).
		emit(&b, "vec1")
	return b.String()
}

func emitDecorr(t *testing.T, data string) string {
	flat := initializer(t, data, "default_decorrelation_matrices").flat()
	offs := initializer(t, data, "default_decorrelation").kids
	if len(offs) != 7 {
		t.Fatalf("default_decorrelation: %d entries, want 7", len(offs))
	}
	if offs[0].val != "NULL" {
		t.Fatalf("default_decorrelation[0] = %q, want NULL", offs[0].val)
	}

	var b strings.Builder
	b.WriteString(`
// The default channel decorrelation matrices, indexed by the channel count of
// the group they apply to. A group of n channels uses an n-by-n matrix, laid
// out one row per line here. Upstream packs all six end to end and indexes
// them through an offset table; this splits them at the offsets that table
// gives. Index 0 is unused.

var defaultDecorrelation = [7][]float32{
	nil,`)
	want := 0
	for n := 1; n <= 6; n++ {
		off := matrixOffset(t, offs[n].val)
		if off != want {
			t.Fatalf("default_decorrelation[%d]: offset %d, want %d", n, off, want)
		}
		if off+n*n > len(flat) {
			t.Fatalf("default_decorrelation[%d]: %d values past the end", n, off+n*n-len(flat))
		}
		fmt.Fprintf(&b, "\n\t{%s},", listRaw(flat[off:off+n*n], n))
		want += n * n
	}
	if want != len(flat) {
		t.Fatalf("default_decorrelation_matrices: %d values used of %d", want, len(flat))
	}
	b.WriteString("\n}\n")
	return b.String()
}

// matrixOffset reads K out of `&default_decorrelation_matrices[K]`.
func matrixOffset(t *testing.T, ref string) int {
	t.Helper()
	i, j := strings.IndexByte(ref, '['), strings.LastIndexByte(ref, ']')
	if i < 0 || j < i {
		t.Fatalf("default_decorrelation entry %q: not a matrix reference", ref)
	}
	n, err := strconv.Atoi(strings.TrimSpace(ref[i+1 : j]))
	if err != nil {
		t.Fatalf("default_decorrelation entry %q: %v", ref, err)
	}
	return n
}
