// Code generated by tablesgen; DO NOT EDIT.
// Regenerate with `WAXFLOW_FFMPEG_SRC=... go generate ./codec/wmapro`.
//
// Black-box parameter artifact (ADR-0001): data only, no decoder logic. WMA
// Pro has no published bitstream spec, so these are extracted from FFmpeg's
// data file, pinned by SHA-256 in tablesgen_test.go, rather than restated from
// a normative document. See THIRD-PARTY-NOTICES.md and
// docs/notes/wma-pro-bitstream.md.

package wmapro

// The default channel decorrelation matrices, indexed by the channel count of
// the group they apply to. A group of n channels uses an n-by-n matrix, laid
// out one row per line here. Upstream packs all six end to end and indexes
// them through an offset table; this splits them at the offsets that table
// gives. Index 0 is unused.

var defaultDecorrelation = [7][]float32{
	nil,
	{
		1.000000,
	},
	{
		0.707031, -0.707031,
		0.707031, 0.707031,
	},
	{
		0.578125, 0.707031, 0.410156,
		0.578125, -0.707031, 0.410156,
		0.578125, 0.000000, -0.816406,
	},
	{
		0.500000, 0.652344, 0.500000, 0.269531,
		0.500000, 0.269531, -0.500000, -0.652344,
		0.500000, -0.269531, -0.500000, 0.652344,
		0.500000, -0.652344, 0.500000, -0.269531,
	},
	{
		0.445312, 0.601562, 0.511719, 0.371094, 0.195312,
		0.445312, 0.371094, -0.195312, -0.601562, -0.511719,
		0.445312, 0.000000, -0.632812, 0.000000, 0.632812,
		0.445312, -0.371094, -0.195312, 0.601562, -0.511719,
		0.445312, -0.601562, 0.511719, -0.371094, 0.195312,
	},
	{
		0.410156, 0.558594, 0.500000, 0.410156, 0.289062, 0.148438,
		0.410156, 0.410156, 0.000000, -0.410156, -0.578125, -0.410156,
		0.410156, 0.148438, -0.500000, -0.410156, 0.289062, 0.558594,
		0.410156, -0.148438, -0.500000, 0.410156, 0.289062, -0.558594,
		0.410156, -0.410156, 0.000000, 0.410156, -0.578125, 0.410156,
		0.410156, -0.558594, 0.500000, -0.410156, 0.289062, -0.148438,
	},
}
