// Code generated by tablesgen; DO NOT EDIT.
// Regenerate with `WAXFLOW_FFMPEG_SRC=... go generate ./codec/wmapro`.
//
// Black-box parameter artifact (ADR-0001): data only, no decoder logic. WMA
// Pro has no published bitstream spec, so these are extracted from FFmpeg's
// data file, pinned by SHA-256 in tablesgen_test.go, rather than restated from
// a normative document. See THIRD-PARTY-NOTICES.md and
// docs/notes/wma-pro-bitstream.md.

package wmapro

// bandEdgeFreqs are the upper edges in Hz that the scale-factor bands are laid
// out on, one band per edge that lands past the previous one. The band table
// is computed per block size from these and the sample rate rather than
// tabulated (docs/notes/wma-pro-bitstream.md).

var bandEdgeFreqs = [28]uint16{
	100, 200, 300, 400, 510, 630, 770,
	920, 1080, 1270, 1480, 1720, 2000, 2320,
	2700, 3150, 3700, 4400, 5300, 6400, 7700,
	9500, 12000, 15500, 20675, 28575, 41375, 63875,
}
