//go:build wmavoicetablesgen

package wmavoice

// Offline extraction of the WMA Voice parameter tables (ADR-0001). Run with:
//
//	WAXFLOW_FFMPEG_SRC=/path/to/ffmpeg/libavcodec go generate ./codec/wmavoice
//
// which is wired to `go test -tags wmavoicetablesgen -run ^TestGenerateTables$`.
//
// WMA Voice, like the rest of the WMA family, has no published bitstream spec,
// so its tables cannot be restated from a normative document the way the AAC
// and SBR tables are. They are extracted instead, mechanically and under a
// SHA-256 pin, from FFmpeg's data file, in the analysis pass ADR-0001
// separates from implementation. Mechanically matters: twenty thousand numbers
// cannot be transcribed by hand and then be trusted, and a reviewer can re-run
// this against the pinned upstream and diff the result.
//
// The pinned files are data, not logic. wmavoice_data.h holds the eight LSP
// vector-quantiser codebooks, the four LSP interpolation coefficient sets, the
// two mean-LSF vectors, the comfort-noise codebook, the four gain codebooks,
// the two adaptive-codebook interpolation filters, and the two postfilter
// tables. One array is taken from wmavoice.c as well, the pitch-adaptive
// window start offsets, because that is where it lives upstream; nothing else
// is read from that file. How each table is indexed, and the biases and scales
// it is read with, are rules rather than data and live in
// docs/notes/wma-voice-bitstream.md.

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

// Pinned upstream: FFmpeg n9.0, commit d32b387f2b0a484599d4587d651891f0c63c4238.
// A changed digest fails loudly rather than silently regenerating different
// tables, the discipline internal/testutil.Vectors uses for fetched vectors.
var pinned = map[string]string{
	"wmavoice_data.h": "47d570cf58e98f8015ac588e6bb8fbbbc99e04b89aa994c781de11e4d119c173",
	"wmavoice.c":      "f4e77847584383f3a3c145ace8b4bbe6eee13811362b0d9923d4f4cc450a4d37",
}

func TestGenerateTables(t *testing.T) {
	dir := os.Getenv("WAXFLOW_FFMPEG_SRC")
	if dir == "" {
		t.Fatal("set WAXFLOW_FFMPEG_SRC to a checked-out ffmpeg libavcodec/ directory")
	}
	src := map[string]string{}
	for name, want := range pinned {
		b, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			t.Fatalf("read %s: %v", name, err)
		}
		b = bytes.ReplaceAll(b, []byte("\r\n"), []byte("\n"))
		// An empty pin prints the digest it would need, which is how a new
		// upstream file gets pinned in the first place.
		if got := hex.EncodeToString(sha256Sum(b)); got != want {
			t.Fatalf("%s: digest %s, pinned %q", name, got, want)
		}
		src[name] = string(b)
	}

	data, code := src["wmavoice_data.h"], src["wmavoice.c"]
	// The go:generate directive rides on the first generated file because the
	// analysis pass ships tables only: this package has no hand-written file
	// yet for it to live in. Move it when one arrives.
	writeFile(t, "tables_lsp.go", genDirective+emitLSP(t, data))
	writeFile(t, "tables_gain.go", emitGain(t, data))
	writeFile(t, "tables_pulse.go", emitPulse(t, data, code))
	writeFile(t, "tables_interp.go", emitInterp(t, data))
	writeFile(t, "tables_denoise.go", emitDenoise(t, data))
}

func sha256Sum(b []byte) []byte { s := sha256.Sum256(b); return s[:] }

const genHeader = "// Code generated by tablesgen; DO NOT EDIT.\n" +
	"// Regenerate with `WAXFLOW_FFMPEG_SRC=... go generate ./codec/wmavoice`.\n" +
	"//\n" +
	"// Black-box parameter artifact (ADR-0001): data only, no decoder logic. WMA\n" +
	"// Voice has no published bitstream spec, so these are extracted from FFmpeg's\n" +
	"// data file, pinned by SHA-256 in tablesgen_test.go, rather than restated from\n" +
	"// a normative document. See THIRD-PARTY-NOTICES.md and\n" +
	"// docs/notes/wma-voice-bitstream.md.\n" +
	"\n" +
	"package wmavoice\n"

const genDirective = "\n//go:generate go test -tags wmavoicetablesgen -run ^TestGenerateTables$ -count=1\n"

func writeFile(t *testing.T, name, body string) {
	t.Helper()
	out, err := format.Source([]byte(genHeader + body))
	if err != nil {
		t.Fatalf("%s: gofmt: %v", name, err)
	}
	if err := os.WriteFile(name, out, 0o644); err != nil {
		t.Fatal(err)
	}
	t.Logf("wrote %s (%d bytes)", name, len(out))
}

// --- C initializer parsing -------------------------------------------------

// node is one parsed C initializer: a scalar when kids is nil, otherwise a
// brace group. The tables here nest at most three deep.
type node struct {
	val  string
	kids []node
}

func (n node) flat() []string {
	if n.kids == nil {
		return []string{n.val}
	}
	var out []string
	for _, k := range n.kids {
		out = append(out, k.flat()...)
	}
	return out
}

// initializer returns the brace group of the named C array. Comments come off
// before the search, so a name mentioned in prose ahead of its declaration
// cannot capture it, and the match needs a non-identifier character to its
// left, so `wmavoice_dq_lsp10i` does not latch onto a longer name ending in
// it. Both would otherwise parse the wrong array and still compile.
func initializer(t *testing.T, src, name string) node {
	t.Helper()
	src = stripComments(src)
	at := -1
	for i := 0; ; {
		j := strings.Index(src[i:], name+"[")
		if j < 0 {
			break
		}
		j += i
		if j == 0 || !isIdentByte(src[j-1]) {
			at = j
			break
		}
		i = j + 1
	}
	if at < 0 {
		t.Fatalf("%s: no declaration found", name)
	}
	j := strings.IndexByte(src[at:], '{')
	if j < 0 {
		t.Fatalf("%s: no initializer", name)
	}
	body, _ := parseGroup(t, src[at+j:], 0)
	return body
}

func isIdentByte(c byte) bool {
	return c == '_' || c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9'
}

func stripComments(s string) string {
	var b strings.Builder
	for i := 0; i < len(s); {
		switch {
		case strings.HasPrefix(s[i:], "/*"):
			e := strings.Index(s[i+2:], "*/")
			if e < 0 {
				return b.String()
			}
			i += 2 + e + 2
		case strings.HasPrefix(s[i:], "//"):
			e := strings.IndexByte(s[i:], '\n')
			if e < 0 {
				return b.String()
			}
			i += e
		default:
			b.WriteByte(s[i])
			i++
		}
	}
	return b.String()
}

// parseGroup consumes the brace group starting at s[at] and returns it plus
// the index just past its closing brace.
func parseGroup(t *testing.T, s string, at int) (node, int) {
	t.Helper()
	if s[at] != '{' {
		t.Fatalf("expected a brace group at %d", at)
	}
	out := node{kids: []node{}}
	var tok strings.Builder
	flush := func() {
		v := strings.TrimSpace(tok.String())
		tok.Reset()
		if v != "" {
			out.kids = append(out.kids, node{val: v})
		}
	}
	for i := at + 1; i < len(s); {
		switch c := s[i]; c {
		case '{':
			// Flush first: a scalar sitting before a nested group belongs
			// ahead of it, and appending the group first would reorder them.
			flush()
			kid, next := parseGroup(t, s, i)
			out.kids = append(out.kids, kid)
			i = next
		case '}':
			flush()
			return out, i + 1
		case ',':
			flush()
			i++
		default:
			tok.WriteByte(c)
			i++
		}
	}
	t.Fatal("unterminated initializer")
	return out, len(s)
}

// scalars returns the named array's leaves, checking the count. Every table
// here is a fixed shape, so a wrong count means a wrong parse.
func scalars(t *testing.T, src, name string, want int) []string {
	t.Helper()
	v := initializer(t, src, name).flat()
	if len(v) != want {
		t.Fatalf("%s: %d values, want %d", name, len(v), want)
	}
	for i := range v {
		v[i] = strings.TrimSpace(v[i])
	}
	return v
}

func ints(t *testing.T, vals []string) []int64 {
	t.Helper()
	out := make([]int64, len(vals))
	for i, v := range vals {
		n, err := strconv.ParseInt(v, 10, 64)
		if err != nil {
			t.Fatalf("parse %q: %v", v, err)
		}
		out[i] = n
	}
	return out
}

// --- emitters --------------------------------------------------------------

// listRaw emits the C literals unchanged, which is what keeps the extraction
// mechanical: no value is reformatted, rounded or re-derived on the way
// through. Go and C agree on the syntax of every literal in these tables.
func listRaw(vals []string, perLine int) string {
	var b strings.Builder
	for i, v := range vals {
		if i%perLine == 0 {
			b.WriteString("\n\t")
		}
		fmt.Fprintf(&b, "%s, ", strings.TrimSpace(v))
	}
	b.WriteString("\n")
	return b.String()
}

func listInts(vals []int64, perLine int) string {
	var b strings.Builder
	for i, v := range vals {
		if i%perLine == 0 {
			b.WriteString("\n\t")
		}
		fmt.Fprintf(&b, "%d, ", v)
	}
	b.WriteString("\n")
	return b.String()
}

// emitFlat writes a one-dimensional array of the given Go element type.
func emitFlat(b *strings.Builder, goName, goType string, vals []string, perLine int) {
	fmt.Fprintf(b, "\nvar %s = [%d]%s{%s}\n", goName, len(vals), goType, listRaw(vals, perLine))
}

// emitRows writes a two-dimensional array, splitting the flat values into rows
// of width cols.
func emitRows(b *strings.Builder, goName, goType string, vals []string, rows, cols, perLine int) {
	fmt.Fprintf(b, "\nvar %s = [%d][%d]%s{", goName, rows, cols, goType)
	for r := 0; r < rows; r++ {
		fmt.Fprintf(b, "\n\t{%s},", listRaw(vals[r*cols:(r+1)*cols], perLine))
	}
	b.WriteString("\n}\n")
}

func emitLSP(t *testing.T, data string) string {
	var b strings.Builder

	b.WriteString(`
// The LSP vector-quantiser codebooks. Each is a flat run of unsigned entries,
// one contiguous block of "num" entries per codebook vector, with the stages
// of a multi-stage quantiser laid end to end in the order the stages are read.
// The dequantised LSF is base + mul*entry summed over the stages, with base
// and mul per stage; both live in docs/notes/wma-voice-bitstream.md because
// they are a handful of constants rather than a table.
//
// The 10-coefficient set:  dqLSP10i is four stages of 256, 64, 32 and 32
// vectors of 10; dqLSP10r is three stages of 128, 64 and 64 vectors of 20.
// The 16-coefficient set is split three ways by coefficient index, 0..4, 5..9
// and 10..15 for the independent form and 0..9, 10..19 and 20..31 for the
// residual form.

`)
	for _, tab := range []struct {
		c, g string
		n    int
	}{
		{"wmavoice_dq_lsp10i", "dqLSP10i", 0xf00},
		{"wmavoice_dq_lsp10r", "dqLSP10r", 0x1400},
		{"wmavoice_dq_lsp16i1", "dqLSP16i1", 0x640},
		{"wmavoice_dq_lsp16i2", "dqLSP16i2", 0x3c0},
		{"wmavoice_dq_lsp16i3", "dqLSP16i3", 0x300},
		{"wmavoice_dq_lsp16r1", "dqLSP16r1", 0x500},
		{"wmavoice_dq_lsp16r2", "dqLSP16r2", 0x500},
		{"wmavoice_dq_lsp16r3", "dqLSP16r3", 0x600},
	} {
		v := ints(t, scalars(t, data, tab.c, tab.n))
		for _, x := range v {
			if x < 0 || x > 255 {
				t.Fatalf("%s: value %d does not fit uint8", tab.c, x)
			}
		}
		fmt.Fprintf(&b, "\nvar %s = [%d]uint8{%s}\n", tab.g, len(v), listInts(v, 20))
	}

	b.WriteString(`
// The LSP inter-frame interpolation coefficients, selected by a 5-bit index in
// the residual form. Each index carries two weight vectors, one per
// interpolated frame; the A set is used when the header's quantiser-mode flag
// is clear and the B set when it is set.

`)
	for _, tab := range []struct {
		c, g string
		n    int
	}{
		{"wmavoice_lsp10_intercoeff_a", "lsp10InterpA", 10},
		{"wmavoice_lsp10_intercoeff_b", "lsp10InterpB", 10},
		{"wmavoice_lsp16_intercoeff_a", "lsp16InterpA", 16},
		{"wmavoice_lsp16_intercoeff_b", "lsp16InterpB", 16},
	} {
		v := scalars(t, data, tab.c, 32*2*tab.n)
		fmt.Fprintf(&b, "\nvar %s = [32][2][%d]float32{", tab.g, tab.n)
		for i := 0; i < 32; i++ {
			b.WriteString("\n\t{")
			for j := 0; j < 2; j++ {
				off := (i*2 + j) * tab.n
				fmt.Fprintf(&b, "\n\t\t{%s},", listRaw(v[off:off+tab.n], tab.n))
			}
			b.WriteString("\n\t},")
		}
		b.WriteString("\n}\n")
	}

	b.WriteString(`
// The mean LSF vectors the dequantised residual is added to, selected by the
// header's default-set flag. Held in float64 because the whole LSP path
// upstream of the LSP-to-LPC conversion is double precision.

`)
	emitRows(&b, "meanLSF10", "float64", scalars(t, data, "wmavoice_mean_lsf10", 2*10), 2, 10, 4)
	emitRows(&b, "meanLSF16", "float64", scalars(t, data, "wmavoice_mean_lsf16", 2*16), 2, 16, 4)
	return b.String()
}

func emitGain(t *testing.T, data string) string {
	var b strings.Builder

	b.WriteString(`
// The gain codebooks. gainSilence is indexed by the 8-bit per-frame gain of a
// silence frame, gainUniversal by the 6-bit per-block gain of a hardcoded
// frame, and gainACB and gainFCB share one 7-bit index per block: gainACB is
// the adaptive-codebook gain outright, and gainFCB is a log-domain term that
// enters the fixed-codebook gain through the predictor described in
// docs/notes/wma-voice-bitstream.md.

`)
	emitFlat(&b, "gainSilence", "float32", scalars(t, data, "wmavoice_gain_silence", 256), 4)
	emitFlat(&b, "gainUniversal", "float32", scalars(t, data, "wmavoice_gain_universal", 64), 4)
	emitFlat(&b, "gainACB", "float32", scalars(t, data, "wmavoice_gain_codebook_acb", 128), 4)
	emitFlat(&b, "gainFCB", "float32", scalars(t, data, "wmavoice_gain_codebook_fcb", 128), 4)
	return b.String()
}

func emitPulse(t *testing.T, data, code string) string {
	var b strings.Builder

	b.WriteString(`
// The comfort-noise codebook: 1000 fixed values a silence or hardcoded frame
// reads a run of block-length entries from, scaled by the frame's gain. The
// offset of the run is transmitted for a hardcoded frame and computed from the
// frame counter for a silence frame, which is why a silence frame's output
// depends on how many frames have been decoded since the stream started.

`)
	emitFlat(&b, "stdCodebook", "float32", scalars(t, data, "wmavoice_std_codebook", 1000), 5)

	b.WriteString(`
// The pitch-adaptive window start offsets, indexed by the 6-bit (or extended
// 8-bit) position field of an AW-pulse frame. This is the one table taken from
// upstream's decoder source rather than its data header, because that is where
// it lives; nothing else is read from that file.

`)
	v := ints(t, scalars(t, code, "start_offset", 94))
	fmt.Fprintf(&b, "\nvar awStartOffsets = [%d]int16{%s}\n", len(v), listInts(v, 12))
	return b.String()
}

func emitInterp(t *testing.T, data string) string {
	var b strings.Builder

	b.WriteString(`
// The two adaptive-codebook interpolation filters. interpAsym is the
// asymmetric-sinc filter used when the pitch is coded once per frame and
// interpolated per sample: 17 taps at 9 fractional phases, laid out phase
// within tap. interpHamming is the Hamming-windowed sinc used when the pitch
// is coded per block: 4 taps at 8 fractional phases, same layout. Both are
// read by the interpolation walk in docs/notes/wma-voice-bitstream.md, which
// pins the index arithmetic.

`)
	emitFlat(&b, "interpAsym", "float32", scalars(t, data, "wmavoice_ipol1_coeffs", 17*9), 9)
	emitFlat(&b, "interpHamming", "float32", scalars(t, data, "wmavoice_ipol2_coeffs", 32), 4)
	return b.String()
}

func emitDenoise(t *testing.T, data string) string {
	var b strings.Builder

	b.WriteString(`
// The two postfilter denoise tables. denoisePower is indexed by the header's
// denoise strength and by a 6-bit bucket of the LPC power spectrum, and
// energyTable turns the resulting gain into a filter magnitude. Both are
// smooth analytic functions upstream tabulates rather than evaluates;
// docs/notes/wma-voice-bitstream.md gives the closed forms, and they are
// tabulated here rather than computed so that the postfilter agrees with the
// reference to the last bits of the table.

`)
	emitFlat(&b, "energyTable", "float32", scalars(t, data, "wmavoice_energy_table", 128), 4)
	emitRows(&b, "denoisePower", "float32", scalars(t, data, "wmavoice_denoise_power_table", 12*64), 12, 64, 4)
	return b.String()
}
